from .MainWindowTranslator import MainWindowTranslator
from .BookWindowTranslator import BookWindowTranslator
from .OptionsWindowTranslator import OptionsWindowTranslator
from .CreateBookWindowTranslator import CreateBookWindowTranslator
from .RecipeWindowTranslator import RecipeWindowTranslator
from .CreateRecipeWindowTranslator import CreateRecipeWindowTranslator
