from .MainWindowTranslator import MainWindowTranslator
from .BookWindowTranslator import BookWindowTranslator
from .OptionsWindowTranslator import OptionsWindowTranslator
from .CreateBookWindowTranslator import CreateBookWindowTranslator
