from .OptionalDataWidgetTranslator import OptionalDataWidgetTranslator
from .IngredientsDataWidgetTranslator import IngredientsDataWidgetTranslator
from .StepsDataWidgetTranslator import StepsDataWidgetTranslator
